name: phys139
channels:
    - pyg
    - pytorch
    - conda-forge
dependencies:
    - python=3.10.10
    - numpy
    - uproot
    - tensorflow
    - xrootd
    - scikit-learn
    - matplotlib
    - pytorch
    - torchvision
    - torchaudio
    - cpuonly
    - pyg
    - mplhep
    - tqdm
    - xgboost
    - jupyter-book==0.15.1
    - jupyter_contrib_nbextensions==0.7.0
    - pip
    - pip:
      - jetnet
      - gdown
      - spektral
      - zenodo_get
      - requests
      - ipywidgets
      - widgetsnbextension
